CREATE TABLE "cities" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"state_id" bigint NOT NULL,
	"state_code" varchar(255) NOT NULL,
	"country_id" bigint NOT NULL,
	"country_code" char(2) NOT NULL,
	"latitude" numeric(10, 8) NOT NULL,
	"longitude" numeric(11, 8) NOT NULL,
	"timezone" varchar(255),
	"created_at" timestamp DEFAULT '2014-01-01 12:01:01' NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"flag" smallint DEFAULT 1 NOT NULL,
	"wikiDataId" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "countries" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "countries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"iso3" char(3),
	"numeric_code" char(3),
	"iso2" char(2),
	"phonecode" varchar(255),
	"capital" varchar(255),
	"currency" varchar(255),
	"currency_name" varchar(255),
	"currency_symbol" varchar(255),
	"tld" varchar(255),
	"native" varchar(255),
	"region" varchar(255),
	"region_id" bigint,
	"subregion" varchar(255),
	"subregion_id" bigint,
	"nationality" varchar(255),
	"timezones" text,
	"translations" text,
	"latitude" numeric(10, 8),
	"longitude" numeric(11, 8),
	"emoji" varchar(191),
	"emojiU" varchar(191),
	"created_at" timestamp,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"flag" smallint DEFAULT 1 NOT NULL,
	"wikiDataId" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "regions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "regions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"translations" text,
	"created_at" timestamp,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"flag" smallint DEFAULT 1 NOT NULL,
	"wikiDataId" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "states" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "states_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"country_id" bigint NOT NULL,
	"country_code" char(2) NOT NULL,
	"fips_code" varchar(255),
	"iso2" varchar(255),
	"iso3166_2" varchar(10),
	"type" varchar(191),
	"level" integer,
	"parent_id" bigint,
	"native" varchar(255),
	"latitude" numeric(10, 8),
	"longitude" numeric(11, 8),
	"timezone" varchar(255),
	"created_at" timestamp,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"flag" smallint DEFAULT 1 NOT NULL,
	"wikiDataId" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "subregions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subregions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"translations" text,
	"region_id" bigint NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"flag" smallint DEFAULT 1 NOT NULL,
	"wikiDataId" varchar(255)
);
--> statement-breakpoint
ALTER TABLE "cities" ADD CONSTRAINT "cities_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "public"."countries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cities" ADD CONSTRAINT "cities_state_id_fkey" FOREIGN KEY ("state_id") REFERENCES "public"."states"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "countries" ADD CONSTRAINT "countries_region_id_fkey" FOREIGN KEY ("region_id") REFERENCES "public"."regions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "countries" ADD CONSTRAINT "countries_subregion_id_fkey" FOREIGN KEY ("subregion_id") REFERENCES "public"."subregions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "states" ADD CONSTRAINT "states_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "public"."countries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subregions" ADD CONSTRAINT "subregions_region_id_fkey" FOREIGN KEY ("region_id") REFERENCES "public"."regions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "cities_country_id_idx" ON "cities" USING btree ("country_id" int8_ops);--> statement-breakpoint
CREATE INDEX "cities_state_id_idx" ON "cities" USING btree ("state_id" int8_ops);--> statement-breakpoint
CREATE INDEX "countries_region_id_idx" ON "countries" USING btree ("region_id" int8_ops);--> statement-breakpoint
CREATE INDEX "countries_subregion_id_idx" ON "countries" USING btree ("subregion_id" int8_ops);--> statement-breakpoint
CREATE INDEX "states_country_id_idx" ON "states" USING btree ("country_id" int8_ops);--> statement-breakpoint
CREATE INDEX "subregions_region_id_idx" ON "subregions" USING btree ("region_id" int8_ops);